version: '3.8'

services:
  backend:
    build:
      context: ..          # Trỏ ra thư mục cha (backend) để thấy requirements.txt
      dockerfile: Docker/Dockerfile
    container_name: tis_backend
    ports:
      - "8000:8000"
    volumes:
      - ..:/app            # Ánh xạ code trực tiếp để cập nhật nhanh
      - backend_media:/app/media
    environment:
      - DEBUG=True
    restart: unless-stopped

volumes:
  backend_media: