# Generated by Django 5.2.13 on 2026-04-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chatmessage_options_remove_chatmessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên khách vãng lai'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='guest_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
