# Generated by Django 5.2.13 on 2026-04-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chatmessage_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
